version: "3.0"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
  backend-dev:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./todo-backend/Dockerfile-dev
    volumes:
      - ./todo-backend:/app
    ports:
      - "7000:7000"
